name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    # Setup SSH
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

    # Deploy
    - name: Deploy to server
      run: |
        ssh -T root@91.211.247.199 <<EOF
          cd /home

          # Pull the latest changes
          git pull origin main

          # Install, build and restart Backend
          cd computer-service/backend
          npm install
          pm2 restart 0

          # Install, build and restart Frontend
          cd ../frontend
          npm install
          npm run build
          pm2 restart 1
        EOF


